# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
project_name: goed2kd
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/goed2kd
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w 
    asmflags:
      # - all=-trimpath={{.Env.GOPATH}}
      - ./dontoptimizeme=-N
    gcflags:
      # - all=-trimpath={{.Env.GOPATH}}

archives:
  -
    id: goed2kd
    formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds_info:
      mode: 0777
    format_overrides:
      - goos: windows
        formats: zip

  

checksum:
  name_template: 'checksums.txt'
  algorithm: sha512



snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers_v2:
  - images:
      - "chenjia404/{{.ProjectName}}"
    tags:
      - "latest"
      - "dev"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: "goreleaser.dockefile"
    extra_files:
      - configs/config.example.yaml
      - configs/config.docker.yaml
